package com.diego.mvi.mvicore

/**
 * The Intent simply describes an intention, or action, or command generated by the user
 * interacting with the system. An intent represents the interaction with the view by the user.
 * The Intent delivers changes that need to be processed by the Model.
 */
interface MviIntent